import assets from '../../assets';

const Images = {
  onBoard1: require('./../../assets/images/ob1.png'),
  adi: require('./../../assets/images/adi.jpg'),
  pc: require('./../../assets/images/pc.jpg'),
  ash: require('./../../assets/images/ash.jpg'),
  utkarsh: require('./../../assets/images/utkarsh.jpeg'),
  md: require('./../../assets/images/md.jpg'),
  onBoard2: require('./../../assets/images/ob2.png'),
  onBoard3: require('./../../assets/images/ob3.png'),
  onBoard4: require('./../../assets/images/ob4.png'),
  desigma: require('./../../assets/images/desigma.png'),
  tree: require('./../../assets/images/tree.png'),
  r1: require('./../../assets/images/r1.png'),
  r2: require('./../../assets/images/r2.png'),
  w1: require('./../../assets/images/w1.jpg'),
  w2: require('./../../assets/images/w2.jpg'),
  cred: require('./../../assets/images/cred.png'),
  cloud: require('./../../assets/images/cloud.png'),
  logo: require('./../../assets/images/Logo.png'),
  car1: require('./../../assets/images/car1.jpeg'),
  car2: require('./../../assets/images/car2.jpg'),
  car3: require('./../../assets/images/car3.jpg'),
  car4: require('./../../assets/images/car4.jpg'),
  car5: require('./../../assets/images/car5.jpg'),
  corn: require('./../../assets/images/corn.png'),
  home: require('./../../assets/images/home.png'),
  crop: require('./../../assets/images/crop.png'),
  store: require('./../../assets/images/store.png'),
  weather: require('./../../assets/images/weather.png'),
  logoLin: require('./../../assets/images/logoLinear.png'),
  logoLin1: require('./../../assets/images/logoLinear2.png'),
  paddy: require('./../../assets/images/rice.png'),
  jowar: require('./../../assets/images/jowar.png'),
  bajra: require('./../../assets/images/bajra.png'),
  ragi: require('./../../assets/images/ragi.png'),
  tur: require('./../../assets/images/tur.png'),
  barley: require('./../../assets/images/barley.png'),
  gram: require('./../../assets/images/gram.png'),
  moong: require('./../../assets/images/moong.png'),
  urad: require('./../../assets/images/urad.png'),
  cotton: require('./../../assets/images/cotton.png'),
  groundnut: require('./../../assets/images/groundnut.png'),
  sunflower: require('./../../assets/images/sunflower.png'),
  soyabean: require('./../../assets/images/soyabean.png'),
  sesame: require('./../../assets/images/sesame.png'),
  wheat: require('./../../assets/images/wheat.png'),
  masur: require('./../../assets/images/masur.png'),
  mustard: require('./../../assets/images/mustard.png'),
  jute: require('./../../assets/images/jute.png'),
  tea: require('./../../assets/images/tea.png'),
  coffee: require('./../../assets/images/coffee.png'),
  sugarcane: require('./../../assets/images/sugarcane.png'),
  menu: require('./../../assets/images/menu.png'),
  back: require('./../../assets/images/back.png'),
};

export default Images;
